config/routes.rb
Rails.application.routes.draw do
  devise_for :models
  resources :fluids
  resources :nurse_notes
  resources :treatment_sheets
  resources :nurse_procedures
  resources :incident_reports
  resources :radio_test_results
  resources :lab_order_lists
  resources :medication_temps
  resources :appointments
  resources :order_requests
  resources :order_masters
  resources :bill_temps do
    resource :download, only: [:show]
    resource :download2, only: [:show]
  end
  resources :admissions
  resources :service_inventory_histories
  resources :bill_histories
  resources :categories
  resources :services_inventories
  resources :test_results
  resources :radiology_requests
  resources :medication_requests
  resources :lab_requests
  resources :clinic_documents
  resources :basic_med_records
  resources :assign_patients
  resources :patients
  resources :roles
  devise_for :users
    resources :store_requests
    resources :dispensaries
  resources :store_inventory_masters
  resources :purchase_receipts
    resources :assigned_requests
    resources :store_inventory_categories
    resources :store_purchases
    resources :dispensaries
    resources :store_purchases do
      post :append, on: :collection
    end
  get 'home/index'

  get 'requests' => 'home#requests'

  get 'assigned_request_page' => 'home#assigned_requests'

  get 'receipts' => 'home#receipts'

  get 'item_purchase' => 'home#item_purchase'

  get 'categories' => 'home#categories'

  get 'dispensing' => 'home#dispensing'

  get 'confirm_dispense' => 'assigned_requests#confirm_dispense'
  get 'checkout' => 'store_requests#checkout'
  post 'retrive' => 'assigned_requests#retrive'
  get 'search' => 'store_inventory_masters#search'
  post 'back_to_form' => 'store_requests#back_to_form'
  post 'submit_to_dispense' => 'assigned_requests#submit_to_dispense'

  post 'modal_form' => 'store_requests#modal_form'

  get 'items_by_category/:store_inventory_category_id', to: 'store_requests#items_by_category'
  get '/store_requests_search' => 'store_requests#store_requests_search'

  get 'store_requests/update_items', as: 'update_items'

  root 'home#index'

  get '/users' => 'users#index'

  get '/users/new' => 'users#new', :as => 'new_user'
  get '/users/:id/edit' => 'users#edit', :as => 'edit_user'
  get '/users/:id' => 'users#show', :as => 'user'
  patch '/users/:id' => 'users#update', :as => 'update_user'
  patch '/patients/:id' => 'patients#update', :as => 'update_patient'
  post 'create_user' => 'users#create', as: :create_user

  post      'update_clinic_documents'                          =>     'clinic_documents#update_clinic_documents'

  get       'remove_contact'                          =>     'users#remove_contact'

  get       'patients_form'                          =>     'patients#patients_form'
  get  'show_patients'          =>     'patients#show_patients'
  get  'edit_patients'          =>     'patients#edit_patients'
  get  'edit_docs'          =>     'assign_patients#edit_docs'
  get  'assign_a_patient'          =>     'patients#assign_a_patient'
  get  'basic_medical'          =>     'assign_patients#basic_medical'
  get  'assign_a_patient2'          =>     'basic_med_records#assign_a_patient2'

  get  'procedure_list'          =>     'assign_patients#procedure_list'

  get 'view_procedure_record' =>     'nurse_procedures#view_procedure_record'

  get 'incident_form'  =>  'incident_reports#incident_form'
  get 'view_report'  =>  'incident_reports#view_report'

  get  'clinic_documentation'          =>     'assign_patients#clinic_documentation'
    get  'appt_documentation'          =>     'appointments#appt_documentation'
  get  'view_documentation'          =>     'assign_patients#view_documentation'
  get  'assign_lab'          =>     'assign_patients#assign_lab'
  get  'assign_med'          =>     'assign_patients#assign_med'
  get  'show_details'          =>     'assign_patients#show_details'
  get  'docs'          =>     'assign_patients#docs'
  get  'lab_docs'          =>     'lab_requests#lab_docs'
  get  'lab_form'          =>     'lab_requests#lab_form'
  get  'view_lab'          =>     'lab_requests#view_lab'
  get  'delete_lab_record'          =>     'lab_requests#delete_lab_record'
  get  'med_docs'          =>     'medication_requests#med_docs'
  get  'med_form'          =>     'medication_requests#med_form'
  get  'view_med'          =>     'medication_requests#view_med'
  get  'other_med'          =>     'medication_requests#other_med'
  get  'other_radio'          =>     'radiology_requests#other_radio'

  get  'radio_docs'          =>     'radiology_requests#radio_docs'
  get  'radio_form'          =>     'radiology_requests#radio_form'
  get  'view_radio'          =>     'radiology_requests#view_radio'
  get 'delete_radio_record'  =>     'radiology_requests#delete_radio_record'

  get  'other_lab'          =>     'lab_requests#other_lab'
  get  'lab_history'          =>     'lab_requests#lab_history'
  get  'enter_results'          =>     'lab_requests#enter_results'
  get  'lab_medical_records'          =>     'lab_requests#lab_medical_records'
  get  'enter_radio_results'   =>     'radiology_requests#enter_radio_results'
  get  'results'          =>     'test_results#results'
  get  'patient_admission'          =>     'admissions#patient_admission'
  get  'admission_doc'          =>     'admissions#admission_doc'
  get 'patient_bill'    => 'bill_histories#patient_bill'
  get 'bill_open'    => 'bill_temps#bill_open'
  get 'outstanding'   => 'bill_temps#outstanding'
  get 'paid'    => 'bill_temps#paid'
  get 'delete_bill_record'    => 'bill_temps#delete_bill_record'

  get 'view_note'  => 'admissions#view_note'
  get 'view_discharge_note' => 'admissions#view_discharge_note'
  get  'view_nurse_record'          =>     'basic_med_records#view_nurse_record'
  post 'assign_to_a_doctor '  =>  'assign_patients#assign_to_a_doctor'
  get  'main_test'          =>     'test_results#main_test'
  get  'indi_radio_result'          =>     'radio_test_results#indi_radio_result'

  get 'close_request' =>  'medication_requests#close_request'
  get 'open_request'  =>   'medication_requests#open_request'

  get 'close_request_rad' =>  'radiology_requests#close_request_rad'
  get 'open_request_rad'  =>   'radiology_requests#open_request_rad'

  get  'order_records'          =>     'order_requests#order_records'
  get  'make_order'          =>     'order_requests#make_order'
  get  'view_order'          =>     'order_requests#view_order'

  get 'delete_order_record' =>     'order_requests#delete_order_record'

  get 'add_room'    =>      'admissions#add_room'
  get 'edit_room'    =>      'admissions#edit_room'
  post 'add_a_room'    =>      'admissions#add_a_room'

  get 'discharge_patient'    =>      'admissions#discharge_patient'
  get 'discharged_list'    =>      'admissions#discharged_list'
  get 'discharged_list_nurses'    =>      'admissions#discharged_list_nurses'
  get 'nurse_admission_list' => 'admissions#nurse_admission_list'

  get 'admission_vitals' => 'admissions#admission_vitals'
  get 'discharge_note' => 'admissions#discharge_note'
  post 'a_discharge_note' => 'admissions#a_discharge_note'

  get 'nurse_admission_vitals_history' =>  'basic_med_records#nurse_admission_vitals_history'
  get 'admission_vital_graph' =>  'basic_med_records#admission_vital_graph'
  get  'admission_basic_medical'          =>     'basic_med_records#admission_basic_medical'

  get  'doctor_admission_vitals_doc'          =>     'admissions#doctor_admission_vitals_doc'
  get  'view_doctor_admission_doc'          =>     'admissions#view_doctor_admission_doc'

  get 'close_order'  =>   'order_requests#close_order'

  get 'patient_appointment' => 'appointments#patient_appointment'

  get 'reception_patient' => 'patients#reception_patient'
  post 'reception_appointment' => 'appointments#reception_appointment'
  get 'doctor_appointment' => 'appointments#doctor_appointment'

  get 'open_med_temp'  => 'medication_temps#open_med_temp'
  get 'close_med_request'   => 'medication_temps#close_med_request'
  get 'delete_med_record'   => 'medication_temps#delete_med_record'

  get 'print_bill'   => 'bill_temps#print_bill'
  get 'print_all_bill'   => 'bill_temps#print_all_bill'

  post 'basic_vitals' => 'assign_patients#basic_vitals'

  get 'import_csv_file' => 'services_inventories#import_csv_file', as: :import_csv_file
  post 'import' => 'services_inventories#import', as: :import

   get  'view_vitals'          =>     'assign_patients#view_vitals'

   get 'print_labresults'   => 'lab_requests#print_labresults'
   get 'print_pharmacy'   => 'bill_temps#print_labresults'
   get 'print_xray'   => 'bill_temps#print_labresults'
   get 'print_ultrasound'   => 'bill_temps#print_labresults'

   get 'view_reciept'   => 'bill_temps#view_reciept'

   get 'set_orders'   => 'home#set_orders'

   get 'patient_profile'   => 'patients#patient_profile'

    get 'patient_treatment' => 'treatment_sheets#patient_treatment'
   get 'new_treatment' => 'treatment_sheets#new_treatment'

   get 'nurses_note' => 'basic_med_records#nurses_note'

   get 'new_nurse_note' => 'basic_med_records#new_nurse_note'
   get 'open_note' => 'basic_med_records#open_note'

   get 'fluids_intake' => 'fluids#fluids_intake'

   get 'new_fluids_intake' => 'fluids#new_fluids_intake'

end

app/models/fluid.rb
class Fluid < ApplicationRecord
end

app/controllers/fluids_controller.rb
class FluidsController < ApplicationController
  before_action :set_fluid, only: [:show, :edit, :update, :destroy]

   layout "doc_patients",:only => [ :fluids_intake]

  # GET /fluids
  # GET /fluids.json
  def index
     @fluid = Fluid.new
    @fluids = Fluid.all
  end


  def fluids_intake
    @fluid = Fluid.new
    patient_id =params[:id]
    @patient_id = patient_id

     @patient_records = Patient.find_by(id: patient_id)
     logger.info "PATEITN ID #{@patient_id}"


      @fluids = Fluid.joins("INNER JOIN patients ON patients.id = fluids.patient_id
                  INNER JOIN users ON users.id  = fluids.user_id").select('surname,other_names,patients.mobile_number,time,fullname,occupation,address,dob,patients.user_id,fluids.patient_id,fluids.id,fluids.status,card_no,fluids.created_at,orals,orals_amount,iv_fluids,fluids_amount,urine_amount,emesis_amount,drainage_amount').where(patient_id: patient_id).order('id desc')

  end


  def new_fluids_intake
     patient_id =params[:id]
    @patient_id = patient_id
    logger.info "PATEITN ID #{@patient_id}"
     @fluid = Fluid.new
  end

  # GET /fluids/1
  # GET /fluids/1.json
  def show
  end

  # GET /fluids/new
  def new
    @fluid = Fluid.new
  end

  # GET /fluids/1/edit
  def edit
  end

  # POST /fluids
  # POST /fluids.json
  def create
    @fluid = Fluid.new(fluid_params)

    respond_to do |format|
      if @fluid.save
        format.html { redirect_back fallback_location: '/', notice: 'Fluid was successfully created.' }
        format.json { render :show, status: :created, location: @fluid }
      else
        format.html { render :new }
        format.json { render json: @fluid.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fluids/1
  # PATCH/PUT /fluids/1.json
  def update
    respond_to do |format|
      if @fluid.update(fluid_params)
        format.html { redirect_to @fluid, notice: 'Fluid was successfully updated.' }
        format.json { render :show, status: :ok, location: @fluid }
      else
        format.html { render :edit }
        format.json { render json: @fluid.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fluids/1
  # DELETE /fluids/1.json
  def destroy
    @fluid.destroy
    respond_to do |format|
      format.html { redirect_to fluids_url, notice: 'Fluid was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fluid
      @fluid = Fluid.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fluid_params
      params.require(:fluid).permit(:orals, :orals_amount, :iv_fluids, :fluids_amount, :urine_amount, :emesis_amount, :drainage_amount, :user_id, :time, :patient_id, :status)
    end
end

app/views/fluids/_form.html.erb
<%= simple_form_for(@fluid) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :orals %>
    <%= f.input :orals_amount %>
    <%= f.input :iv_fluids %>
    <%= f.input :fluids_amount %>
    <%= f.input :urine_amount %>
    <%= f.input :emesis_amount %>
    <%= f.input :drainage_amount %>
    <%= f.input :user_id %>
    <%= f.input :time %>
    <%= f.input :patient_id %>
    <%= f.input :status %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/fluids/_new_fluids_intake.html.erb
<%= simple_form_for(@fluid) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">

   <%= f.input :time, label: "Time", as: :string,input_html: { id: "datetimepicker",placeholder: 'Choose time' }  %>
   </div>
   
      <%= f.input :orals,label: "Type of Orals", as: :text %>
       <%= f.input :orals_amount,label: "Orals Amount", as: :integer %>
       <%= f.input :iv_fluids,label: "Type of IV fluids", as: :text %>
       <%= f.input :fluids_amount,label: "Fluids Amount", as: :integer %>
       <%= f.input :urine_amount,label: "Urine Amount", as: :integer %>
       <%= f.input :emesis_amount,label: "Emesis Amount", as: :integer %>
       <%= f.input :drainage_amount,label: "Drainage Amount", as: :integer %>

   

   

  <div class="form-inputs">
    <%= f.input :user_id, :as=> :hidden,input_html: {value: current_user.id} %>
    <% logger.info "role in index: #{current_user.role_id}" %>

</div>

 <div class="form-inputs">
   
    <%= f.input :patient_id, :as=> :hidden,input_html: {value: @patient_id} %>
    <% logger.info "role in index: #{current_user.role_id}" %>

      <%= f.input :status, :as=> :hidden,input_html: {value: 0} %>

</div>


  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>


<script type="text/javascript">
        $('#datetimepicker').datetimepicker({
          format : 'HH:mm:ss'
        })
        $('[data-behaviour~=datetimepicker]').datetimepicker();
      </script> 

app/views/fluids/edit.html.erb
<h1>Editing Fluid</h1>

<%= render 'form' %>

<%= link_to 'Show', @fluid %> |
<%= link_to 'Back', fluids_path %>

app/views/fluids/fluids_intake.html.erb
<section id="main-content">
  <section class="wrapper">
     
    <div class="table-agile-info">
 <div class="panel panel-default">

                             
<br>
<br>
    <div class="panel-heading">
   Fluids Intake
    </div>
    
    <div style="overflow-x:auto;">
      <table  class="table" ui-jq="footable" ui-options='{
        "paging": {
          "enabled": true
        },
        "filtering": {
          "enabled": true
        },
        "sorting": {
          "enabled": true
        }}'>
        <thead>
         <tr>
    <!--    <th>Nurses Note</th> -->
                <th>Time</th>
                 <th>Type of Orals</th>
                  <th>Amount</th>
                   <th>Type of IV fluids</th>
                   <th>Amount</th>
                     <th>Urine Amount</th>
                       <th>Emesis Amount</th>
                         <th>Drainage Amount</th>
                <th>Written by</th>
      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
     <% @fluids.each do |fluid| %>
      <tr>
        <!-- <td ><%#= nurse_note.notes %></td> -->
        <td id="whitespace"><%= fluid.time.strftime("%B %d, %Y %H:%M") %></td>
        <td id="whitespace"><%= fluid.orals %></td>
          <td id="whitespace"><%= fluid.orals_amount %></td>
            <td id="whitespace"><%= fluid.iv_fluids %></td>
              <td id="whitespace"><%= fluid.fluids_amount %></td>
               <td id="whitespace"><%= fluid.urine_amount %></td>
                <td id="whitespace"><%= fluid.emesis_amount %></td>
                 <td id="whitespace"><%= fluid.drainage_amount %></td>
         <td id="whitespace"><%= fluid.fullname %></td>
         <td ><%#= link_to 'Open Note', open_note_path(:id => nurse_note.created_at), {:remote => true, class:'"btn btn-warning btn-sm btn3d"','data-toggle' =>  "modal", 'data-target' => '#myModal4'} %></td>
        
 
      </tr>
    <% end %>
  </tbody>
</table>

<br>


       <center>

<%= link_to 'Record Fluids Intake', new_fluids_intake_path(:id => @patient_id), {:remote => true, :class => "btn btn-primary btn-sm" ,'data-toggle' =>  "modal", 'data-target' => '#myModal'} %>

     </center>   

  </div>
</div>
</section>
 
</section>


<div id="myModal4" class="modal fade" role="dialog">
  <div class="modal-dialog">


    <div class="modal-content" >
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title"> Notes</h4>
      </div>
      <div class="modal-body">
      <%#= render "open_note" %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>





<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <div class="modal-content" >
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title"> Record Fluids</h4>
      </div>
       <div class="modal-body" id = 'fire'>
      <%= render "new_fluids_intake" %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>

app/views/fluids/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Fluids</h1>

<table>
  <thead>
    <tr>
      <th>Orals</th>
      <th>Orals amount</th>
      <th>Iv fluids</th>
      <th>Fluids amount</th>
      <th>Urine amount</th>
      <th>Emesis amount</th>
      <th>Drainage amount</th>
      <th>User</th>
      <th>Time</th>
      <th>Patient</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fluids.each do |fluid| %>
      <tr>
        <td><%= fluid.orals %></td>
        <td><%= fluid.orals_amount %></td>
        <td><%= fluid.iv_fluids %></td>
        <td><%= fluid.fluids_amount %></td>
        <td><%= fluid.urine_amount %></td>
        <td><%= fluid.emesis_amount %></td>
        <td><%= fluid.drainage_amount %></td>
        <td><%= fluid.user_id %></td>
        <td><%= fluid.time %></td>
        <td><%= fluid.patient_id %></td>
        <td><%= fluid.status %></td>
        <td><%= link_to 'Show', fluid %></td>
        <td><%= link_to 'Edit', edit_fluid_path(fluid) %></td>
        <td><%= link_to 'Destroy', fluid, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fluid', new_fluid_path %>

app/views/fluids/new.html.erb
<h1>New Fluid</h1>

<%= render 'form' %>

<%= link_to 'Back', fluids_path %>

app/views/fluids/new_fluids_intake.js.erb
$("#fire").html("<%= escape_javascript(render 'fluids/new_fluids_intake') %>");
 $('#modal-window').modal('show');

app/views/fluids/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Orals:</strong>
  <%= @fluid.orals %>
</p>

<p>
  <strong>Orals amount:</strong>
  <%= @fluid.orals_amount %>
</p>

<p>
  <strong>Iv fluids:</strong>
  <%= @fluid.iv_fluids %>
</p>

<p>
  <strong>Fluids amount:</strong>
  <%= @fluid.fluids_amount %>
</p>

<p>
  <strong>Urine amount:</strong>
  <%= @fluid.urine_amount %>
</p>

<p>
  <strong>Emesis amount:</strong>
  <%= @fluid.emesis_amount %>
</p>

<p>
  <strong>Drainage amount:</strong>
  <%= @fluid.drainage_amount %>
</p>

<p>
  <strong>User:</strong>
  <%= @fluid.user_id %>
</p>

<p>
  <strong>Time:</strong>
  <%= @fluid.time %>
</p>

<p>
  <strong>Patient:</strong>
  <%= @fluid.patient_id %>
</p>

<p>
  <strong>Status:</strong>
  <%= @fluid.status %>
</p>

<%= link_to 'Edit', edit_fluid_path(@fluid) %> |
<%= link_to 'Back', fluids_path %>