config/routes.rb
Rails.application.routes.draw do
  devise_for :models
  resources :fluids
  resources :nurse_notes
  resources :treatment_sheets
  resources :nurse_procedures
  resources :incident_reports
  resources :radio_test_results
  resources :lab_order_lists
  resources :medication_temps
  resources :appointments
  resources :order_requests
  resources :order_masters
  resources :bill_temps do
    resource :download, only: [:show]
    resource :download2, only: [:show]
  end
  resources :admissions
  resources :service_inventory_histories
  resources :bill_histories
  resources :categories
  resources :services_inventories
  resources :test_results
  resources :radiology_requests
  resources :medication_requests
  resources :lab_requests
  resources :clinic_documents
  resources :basic_med_records
  resources :assign_patients
  resources :patients
  resources :roles
  devise_for :users
    resources :store_requests
    resources :dispensaries
  resources :store_inventory_masters
  resources :purchase_receipts
    resources :assigned_requests
    resources :store_inventory_categories
    resources :store_purchases
    resources :dispensaries
    resources :store_purchases do
      post :append, on: :collection
    end
  get 'home/index'

  get 'requests' => 'home#requests'

  get 'assigned_request_page' => 'home#assigned_requests'

  get 'receipts' => 'home#receipts'

  get 'item_purchase' => 'home#item_purchase'

  get 'categories' => 'home#categories'

  get 'dispensing' => 'home#dispensing'

  get 'confirm_dispense' => 'assigned_requests#confirm_dispense'
  get 'checkout' => 'store_requests#checkout'
  post 'retrive' => 'assigned_requests#retrive'
  get 'search' => 'store_inventory_masters#search'
  post 'back_to_form' => 'store_requests#back_to_form'
  post 'submit_to_dispense' => 'assigned_requests#submit_to_dispense'

  post 'modal_form' => 'store_requests#modal_form'

  get 'items_by_category/:store_inventory_category_id', to: 'store_requests#items_by_category'
  get '/store_requests_search' => 'store_requests#store_requests_search'

  get 'store_requests/update_items', as: 'update_items'

  root 'home#index'

  get '/users' => 'users#index'

  get '/users/new' => 'users#new', :as => 'new_user'
  get '/users/:id/edit' => 'users#edit', :as => 'edit_user'
  get '/users/:id' => 'users#show', :as => 'user'
  patch '/users/:id' => 'users#update', :as => 'update_user'
  patch '/patients/:id' => 'patients#update', :as => 'update_patient'
  post 'create_user' => 'users#create', as: :create_user

  post      'update_clinic_documents'                          =>     'clinic_documents#update_clinic_documents'

  get       'remove_contact'                          =>     'users#remove_contact'

  get       'patients_form'                          =>     'patients#patients_form'
  get  'show_patients'          =>     'patients#show_patients'
  get  'edit_patients'          =>     'patients#edit_patients'
  get  'edit_docs'          =>     'assign_patients#edit_docs'
  get  'assign_a_patient'          =>     'patients#assign_a_patient'
  get  'basic_medical'          =>     'assign_patients#basic_medical'
  get  'assign_a_patient2'          =>     'basic_med_records#assign_a_patient2'

  get  'procedure_list'          =>     'assign_patients#procedure_list'

  get 'view_procedure_record' =>     'nurse_procedures#view_procedure_record'

  get 'incident_form'  =>  'incident_reports#incident_form'
  get 'view_report'  =>  'incident_reports#view_report'

  get  'clinic_documentation'          =>     'assign_patients#clinic_documentation'
    get  'appt_documentation'          =>     'appointments#appt_documentation'
  get  'view_documentation'          =>     'assign_patients#view_documentation'
  get  'assign_lab'          =>     'assign_patients#assign_lab'
  get  'assign_med'          =>     'assign_patients#assign_med'
  get  'show_details'          =>     'assign_patients#show_details'
  get  'docs'          =>     'assign_patients#docs'
  get  'lab_docs'          =>     'lab_requests#lab_docs'
  get  'lab_form'          =>     'lab_requests#lab_form'
  get  'view_lab'          =>     'lab_requests#view_lab'
  get  'delete_lab_record'          =>     'lab_requests#delete_lab_record'
  get  'med_docs'          =>     'medication_requests#med_docs'
  get  'med_form'          =>     'medication_requests#med_form'
  get  'view_med'          =>     'medication_requests#view_med'
  get  'other_med'          =>     'medication_requests#other_med'
  get  'other_radio'          =>     'radiology_requests#other_radio'

  get  'radio_docs'          =>     'radiology_requests#radio_docs'
  get  'radio_form'          =>     'radiology_requests#radio_form'
  get  'view_radio'          =>     'radiology_requests#view_radio'
  get 'delete_radio_record'  =>     'radiology_requests#delete_radio_record'

  get  'other_lab'          =>     'lab_requests#other_lab'
  get  'lab_history'          =>     'lab_requests#lab_history'
  get  'enter_results'          =>     'lab_requests#enter_results'
  get  'lab_medical_records'          =>     'lab_requests#lab_medical_records'
  get  'enter_radio_results'   =>     'radiology_requests#enter_radio_results'
  get  'results'          =>     'test_results#results'
  get  'patient_admission'          =>     'admissions#patient_admission'
  get  'admission_doc'          =>     'admissions#admission_doc'
  get 'patient_bill'    => 'bill_histories#patient_bill'
  get 'bill_open'    => 'bill_temps#bill_open'
  get 'outstanding'   => 'bill_temps#outstanding'
  get 'paid'    => 'bill_temps#paid'
  get 'delete_bill_record'    => 'bill_temps#delete_bill_record'

  get 'view_note'  => 'admissions#view_note'
  get 'view_discharge_note' => 'admissions#view_discharge_note'
  get  'view_nurse_record'          =>     'basic_med_records#view_nurse_record'
  post 'assign_to_a_doctor '  =>  'assign_patients#assign_to_a_doctor'
  get  'main_test'          =>     'test_results#main_test'
  get  'indi_radio_result'          =>     'radio_test_results#indi_radio_result'

  get 'close_request' =>  'medication_requests#close_request'
  get 'open_request'  =>   'medication_requests#open_request'

  get 'close_request_rad' =>  'radiology_requests#close_request_rad'
  get 'open_request_rad'  =>   'radiology_requests#open_request_rad'

  get  'order_records'          =>     'order_requests#order_records'
  get  'make_order'          =>     'order_requests#make_order'
  get  'view_order'          =>     'order_requests#view_order'

  get 'delete_order_record' =>     'order_requests#delete_order_record'

  get 'add_room'    =>      'admissions#add_room'
  get 'edit_room'    =>      'admissions#edit_room'
  post 'add_a_room'    =>      'admissions#add_a_room'

  get 'discharge_patient'    =>      'admissions#discharge_patient'
  get 'discharged_list'    =>      'admissions#discharged_list'
  get 'discharged_list_nurses'    =>      'admissions#discharged_list_nurses'
  get 'nurse_admission_list' => 'admissions#nurse_admission_list'

  get 'admission_vitals' => 'admissions#admission_vitals'
  get 'discharge_note' => 'admissions#discharge_note'
  post 'a_discharge_note' => 'admissions#a_discharge_note'

  get 'nurse_admission_vitals_history' =>  'basic_med_records#nurse_admission_vitals_history'
  get 'admission_vital_graph' =>  'basic_med_records#admission_vital_graph'
  get  'admission_basic_medical'          =>     'basic_med_records#admission_basic_medical'

  get  'doctor_admission_vitals_doc'          =>     'admissions#doctor_admission_vitals_doc'
  get  'view_doctor_admission_doc'          =>     'admissions#view_doctor_admission_doc'

  get 'close_order'  =>   'order_requests#close_order'

  get 'patient_appointment' => 'appointments#patient_appointment'

  get 'reception_patient' => 'patients#reception_patient'
  post 'reception_appointment' => 'appointments#reception_appointment'
  get 'doctor_appointment' => 'appointments#doctor_appointment'

  get 'open_med_temp'  => 'medication_temps#open_med_temp'
  get 'close_med_request'   => 'medication_temps#close_med_request'
  get 'delete_med_record'   => 'medication_temps#delete_med_record'

  get 'print_bill'   => 'bill_temps#print_bill'
  get 'print_all_bill'   => 'bill_temps#print_all_bill'

  post 'basic_vitals' => 'assign_patients#basic_vitals'

  get 'import_csv_file' => 'services_inventories#import_csv_file', as: :import_csv_file
  post 'import' => 'services_inventories#import', as: :import

   get  'view_vitals'          =>     'assign_patients#view_vitals'

   get 'print_labresults'   => 'lab_requests#print_labresults'
   get 'print_pharmacy'   => 'bill_temps#print_labresults'
   get 'print_xray'   => 'bill_temps#print_labresults'
   get 'print_ultrasound'   => 'bill_temps#print_labresults'

   get 'view_reciept'   => 'bill_temps#view_reciept'

   get 'set_orders'   => 'home#set_orders'

   get 'patient_profile'   => 'patients#patient_profile'

    get 'patient_treatment' => 'treatment_sheets#patient_treatment'
   get 'new_treatment' => 'treatment_sheets#new_treatment'

   get 'nurses_note' => 'basic_med_records#nurses_note'

   get 'new_nurse_note' => 'basic_med_records#new_nurse_note'
   get 'open_note' => 'basic_med_records#open_note'

   get 'fluids_intake' => 'fluids#fluids_intake'

   get 'new_fluids_intake' => 'fluids#new_fluids_intake'

end

app/models/order_request.rb
class OrderRequest < ApplicationRecord


	def to_label

  #{self.service_name}  #{self.price}

end
end

app/helpers/order_requests_helper.rb
module OrderRequestsHelper
end

app/views/order_requests/_form.html.erb
<%= simple_form_for(@order_request) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :patient_id %>
    <%= f.input :user_id %>
    <%= f.input :personnel_id %>
    <%= f.input :status %>
    <%= f.input :order_master_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/order_requests/_make_order.html.erb
 <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  
  <script src="/assets/bootstrap-combobox.js"></script>


   <div class="table-agile-info" role="form">

 
   <%= simple_form_for(@order_request) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

 

                             


  <div class="form-group">
 
    <%#= f.input :personnel_id,label: "Lab Technician", collection: Role.where("id = 2"), label_method: :role_name, value_method: :id,class:'form-control'%>
  </div>


  <div class="form-inputs">
    <%= f.input :user_id, :as=> :hidden,input_html: {value: current_user.role_id} %>
    <% logger.info "role in index: #{current_user.role_id}" %>

</div>

<center>
  <div class="form-group">
 
    
      <%= f.input :service_id, label: "Type/Select Medication orders", :id => "push_left", collection:   @services_inventories,label_method: 

              lambda { 

               |plan| "#{plan.service_name} - Ghc #{plan.price}" 

              }  , value_method: :id, input_html:{ class:"combobox", data: {placeholder: "Order List" } }%>


  </div>



  <div class="qty-width">

    <%= f.input :drug_quantity,label: "Quantity", :as => "integer" , input_html: {value: f.object.service_id || '1'} %>

  </div>

  <div class="form-group">

    <%= f.input :dosage,label: "Medication Dosage/ Instructions/Comments/Prescriptions", as: :text, input_html: { rows: "4"}  %>

  </div>
</center>

<div class="form-inputs">
  <% if (defined?(@patient_id)).nil? %>
    <%= f.input :patient_id,:as=> :hidden %>

   <% else  %>
  <%= f.input :patient_id, :as=> :hidden,input_html: {value: @patient_id} %>
<% logger.info "Rnning" %>
 <% logger.info "patient in index: #{@patient_id}" %>

  </div>

  <div class="form-inputs">
    <%= f.input :status, :as=> :hidden, input_html: {value: 0 } %>

  </div>

   <div class="form-inputs">
    <%= f.input :delete_status, :as=> :hidden, input_html: {value: 0 } %>

  </div>

<center>

   <div class="form-actions">
    <%#= f.button :submit %>
     <%= f.submit "Submit Order",:class => "btn btn-primary btn-sm" %>
  </div>
  </center>

<% end %>

<% end %>

</div>




<script type="text/javascript">
    $(document).ready(function(){
         $('form').attr('autocomplete', 'off');
        
         $('.combobox').combobox();

   $('span.input-group-addon').addClass("hidden");
  
    });
</script>

app/views/order_requests/_view_order.html.erb
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
 
        <table class="custab table table-striped table-hover table-bordered">
<br>
        
           
                             
<br>
<br>
               
               <div class="cent"  ><b><p>Order Requested</p></b></div>                 
        
           
              
          <!--   <td style="background-color:rgba(110, 129, 149, 0.96);color:#fbfbff">Order requested</td> -->
            <!-- <td style="background-color:rgba(251, 251, 255, 0.96);color:#000000"> -->
            <center>
                 <%=  @document1[0].order_name %>
              
            </center>
         
           <!--  </td> -->
             
        <!--   </tr> -->
          



 
          
        <% #end %>
          
         
           </table>
          
  </div>
</div>

app/views/order_requests/close_order.js.erb
<% if @order_id.status == true %>
    $(".order-<%= @order_id.id %> > a").html('Close order').removeClass('btn-warning').addClass('btn-success')
<% else %>
    $(".order-<%= @order_id.id %> > a").html('Order closed').removeClass('btn-success').addClass('btn-warning')
<% end %>
$("#order_status-status-<%= @order_id.id %>").html("<%= @order_id.status %>")

app/views/order_requests/edit.html.erb
<h1>Editing Order Request</h1>

<%= render 'form' %>

<%= link_to 'Show', @order_request %> |
<%= link_to 'Back', order_requests_path %>

app/views/order_requests/index.html.erb
<section id="main-content">
  <section class="wrapper">
     
    <div class="table-agile-info">
 <div class="panel panel-default">
             
<br>
<br>
    <div class="panel-heading">
   Order Requests
    </div>
    
    <div style="overflow-x:auto;">
      <table class="table" ui-jq="footable" ui-options='{
        "paging": {
          "enabled": true
        },
        "filtering": {
          "enabled": true
        },
        "sorting": {
          "enabled": true
        }}'>
        <thead>
          <tr>

              <th data-breakpoints="xs">No</th> 
      
      <th>Patient No</th>
      <th>Name</th>
      <th>Order Name</th>
       <th>Status</th>
       <th>Date</th>
      <th>Created by</th>
       <th>status</th>
       
      
      <th colspan="3"></th>
      <th colspan="3"></th>
      <th colspan="3"></th>

          </tr>
        </thead>
        <tbody>
      <% count=1 %>

           <% @order_requests.each do |order| %>
      <tr>
         
        <td><%= count %></td> 
        
          <td><%= order.card_no%></td>
         <td><%= order.other_names + " " +  order.surname %></td>
           <td><%= order.service_name %></td>
         <td><%= "Ordered" %></td>
          <td><%= order.created_at %></td>
         <td><%= order.fullname %></td>
         


<td class="order-<%= order.id %>">
    <%= link_to "#{ order.status ? 'Closed' : 'Close Order' }", close_order_path(:id => order.created_at),{remote: :true, class: "btn btn-xs btn-#{ order.status  ? 'success' : 'warning' }"} %>
</td>

<!-- ,:data =>{disable_with:  "<i class='fa fa-refresh fa-spin'></i> Closing order..." } -->
    


<!--            <td id = "closed">
    <%#= link_to "#{ order.status ? 'Closed' : 'Close Order' }", close_order_path(:id => order.created_at), remote: :true, class: "btn btn-xs btn-#{ order.status ? 'success' : 'warning' }"  %>
</td> -->


      

       <% count=count+1 %> 
    <% end %>
       
           

        </tbody>
      </table>
        <center>
	<div class="digg_pagination">
	<%= will_paginate @order_requests %>
	</div>
</center>

       <center>

     </center>   

  </div>
</div>
</section>
 
</section>









<div id="myModal1" class="modal fade" role="dialog">
  <div class="modal-dialog">


    <div class="modal-content" >
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title"> Order Details</h4>
      </div>
      <div class="modal-body" id = 'boom2'>
      <%#= render "view_order" %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>

app/views/order_requests/make_order.js.erb
$("#boom").html("<%= escape_javascript(render 'order_requests/make_order') %>");
 $('#modal-window').modal('show');

app/views/order_requests/new.html.erb
<h1>New Order Request</h1>

<%= render 'form' %>

<%= link_to 'Back', order_requests_path %>

app/views/order_requests/order_records.html.erb
<section id="main-content">
  <section class="wrapper">
    <div class="table-agile-info">
      <div class="panel panel-default">
        <br>
        <br>
        <div class="panel-heading">
          Order Requests
        </div>
        <div style="overflow-x:auto;">
          <table class="table" ui-jq="footable" ui-options='{
        "paging": {
          "enabled": true
        },
        "filtering": {
          "enabled": true
        },
        "sorting": {
          "enabled": true
        }}'>
            <thead>
              <tr>
                <th data-breakpoints="xs">No</th>
                <th>Patient No</th>
                <th>Name</th>
                <th>Order Name</th>
                <th>Quantity</th>
                <th>Dosage</th>
                <th>Status</th>
                <th>Date</th>
                <th>Created by</th>
                <th colspan="3">   <% if current_user.role_id == 1 %>
                    <%= link_to  'New  Order ', make_order_path(:id => @patient_id), {:remote => true, :class => "btn btn-primary btn-sm" ,'data-toggle' =>  "modal", 'data-target' => '#myModal'} %>
                  <% else%>
                  <% end %></th>
                <th colspan="3"></th>
                <th colspan="3">  </th>
              </tr>
            </thead>
            <tbody>
              <% count=1 %>
              <% @order_requests.each do |order| %>
                <tr>
                  <td id="whitespace"><%= count %></td>
                  <td id="whitespace"><%= order.card_no%></td>
                  <td id="whitespace"><%= order.other_names + " " +  order.surname %></td>
                  <td id="whitespace"><%= order.service_name %></td>
                  <td id="whitespace"><%= order.drug_quantity %></td>
                  <td id="whitespace"><%= order.dosage %></td>
                  <% if order.status == false %>
                    <td id="whitespace"><%= "Ordered" %></td>
                  <%else %>
                    <td id="whitespace"><%= "Order closed" %></td>
                  <%end %>
                  <td id="whitespace"><%= order.created_at.strftime("%B %d, %Y %H:%M") %></td>
                  <td><%= order.fullname %></td>
                  <td id="whitespace" ><%= link_to 'Delete', delete_order_record_path(:created_at => order.created_at),
                {class:'"btn btn-info btn-sm btn3d"', data: { confirm: "Do you want to delete this record?" }}%></td>
                </td>
              </tr>
              <% count=count+1 %>
            <% end %>
          </tbody>
        </table>
        <center>
          <% if current_user.role_id == 1 %>
            <%= link_to  'New  Order ', make_order_path(:id => @patient_id), {:remote => true, :class => "btn btn-primary btn-sm" ,'data-toggle' =>  "modal", 'data-target' => '#myModal'} %>
          <% else%>
          <% end %>
        </center>
        <br>
        <center>
          <div class="digg_pagination">
            <%= will_paginate @order_requests %>
          </div>
        </center>
      </div>
    </div>
  </section>
</section>
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content" >
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title"> Make Order</h4>
      </div>
      <div class="modal-body" id = 'boom'>
        <%= render "make_order" %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
<div id="myModal1" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content" >
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title"> Order Details</h4>
      </div>
      <div class="modal-body" id = 'boom2'>
        <%#= render "view_order" %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/order_requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Patient:</strong>
  <%= @order_request.patient_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @order_request.user_id %>
</p>

<p>
  <strong>Personnel:</strong>
  <%= @order_request.personnel_id %>
</p>

<p>
  <strong>Status:</strong>
  <%= @order_request.status %>
</p>

<p>
  <strong>Order master:</strong>
  <%= @order_request.order_master_id %>
</p>

<%= link_to 'Edit', edit_order_request_path(@order_request) %> |
<%= link_to 'Back', order_requests_path %>

app/views/order_requests/view_order.js.erb
$("#boom2").html("<%= escape_javascript(render 'order_requests/view_order') %>");
$("#modal-window").html("<%= escape_javascript(render 'order_requests/view_order') %>");
 $('#modal-window').modal('show');