config/routes.rb
Rails.application.routes.draw do
  devise_for :models
  resources :fluids
  resources :nurse_notes
  resources :treatment_sheets
  resources :nurse_procedures
  resources :incident_reports
  resources :radio_test_results
  resources :lab_order_lists
  resources :medication_temps
  resources :appointments
  resources :order_requests
  resources :order_masters
  resources :bill_temps do
    resource :download, only: [:show]
    resource :download2, only: [:show]
  end
  resources :admissions
  resources :service_inventory_histories
  resources :bill_histories
  resources :categories
  resources :services_inventories
  resources :test_results
  resources :radiology_requests
  resources :medication_requests
  resources :lab_requests
  resources :clinic_documents
  resources :basic_med_records
  resources :assign_patients
  resources :patients
  resources :roles
  devise_for :users
    resources :store_requests
    resources :dispensaries
  resources :store_inventory_masters
  resources :purchase_receipts
    resources :assigned_requests
    resources :store_inventory_categories
    resources :store_purchases
    resources :dispensaries
    resources :store_purchases do
      post :append, on: :collection
    end
  get 'home/index'

  get 'requests' => 'home#requests'

  get 'assigned_request_page' => 'home#assigned_requests'

  get 'receipts' => 'home#receipts'

  get 'item_purchase' => 'home#item_purchase'

  get 'categories' => 'home#categories'

  get 'dispensing' => 'home#dispensing'

  get 'confirm_dispense' => 'assigned_requests#confirm_dispense'
  get 'checkout' => 'store_requests#checkout'
  post 'retrive' => 'assigned_requests#retrive'
  get 'search' => 'store_inventory_masters#search'
  post 'back_to_form' => 'store_requests#back_to_form'
  post 'submit_to_dispense' => 'assigned_requests#submit_to_dispense'

  post 'modal_form' => 'store_requests#modal_form'

  get 'items_by_category/:store_inventory_category_id', to: 'store_requests#items_by_category'
  get '/store_requests_search' => 'store_requests#store_requests_search'

  get 'store_requests/update_items', as: 'update_items'

  root 'home#index'

  get '/users' => 'users#index'

  get '/users/new' => 'users#new', :as => 'new_user'
  get '/users/:id/edit' => 'users#edit', :as => 'edit_user'
  get '/users/:id' => 'users#show', :as => 'user'
  patch '/users/:id' => 'users#update', :as => 'update_user'
  patch '/patients/:id' => 'patients#update', :as => 'update_patient'
  post 'create_user' => 'users#create', as: :create_user

  post      'update_clinic_documents'                          =>     'clinic_documents#update_clinic_documents'

  get       'remove_contact'                          =>     'users#remove_contact'

  get       'patients_form'                          =>     'patients#patients_form'
  get  'show_patients'          =>     'patients#show_patients'
  get  'edit_patients'          =>     'patients#edit_patients'
  get  'edit_docs'          =>     'assign_patients#edit_docs'
  get  'assign_a_patient'          =>     'patients#assign_a_patient'
  get  'basic_medical'          =>     'assign_patients#basic_medical'
  get  'assign_a_patient2'          =>     'basic_med_records#assign_a_patient2'

  get  'procedure_list'          =>     'assign_patients#procedure_list'

  get 'view_procedure_record' =>     'nurse_procedures#view_procedure_record'

  get 'incident_form'  =>  'incident_reports#incident_form'
  get 'view_report'  =>  'incident_reports#view_report'

  get  'clinic_documentation'          =>     'assign_patients#clinic_documentation'
    get  'appt_documentation'          =>     'appointments#appt_documentation'
  get  'view_documentation'          =>     'assign_patients#view_documentation'
  get  'assign_lab'          =>     'assign_patients#assign_lab'
  get  'assign_med'          =>     'assign_patients#assign_med'
  get  'show_details'          =>     'assign_patients#show_details'
  get  'docs'          =>     'assign_patients#docs'
  get  'lab_docs'          =>     'lab_requests#lab_docs'
  get  'lab_form'          =>     'lab_requests#lab_form'
  get  'view_lab'          =>     'lab_requests#view_lab'
  get  'delete_lab_record'          =>     'lab_requests#delete_lab_record'
  get  'med_docs'          =>     'medication_requests#med_docs'
  get  'med_form'          =>     'medication_requests#med_form'
  get  'view_med'          =>     'medication_requests#view_med'
  get  'other_med'          =>     'medication_requests#other_med'
  get  'other_radio'          =>     'radiology_requests#other_radio'

  get  'radio_docs'          =>     'radiology_requests#radio_docs'
  get  'radio_form'          =>     'radiology_requests#radio_form'
  get  'view_radio'          =>     'radiology_requests#view_radio'
  get 'delete_radio_record'  =>     'radiology_requests#delete_radio_record'

  get  'other_lab'          =>     'lab_requests#other_lab'
  get  'lab_history'          =>     'lab_requests#lab_history'
  get  'enter_results'          =>     'lab_requests#enter_results'
  get  'lab_medical_records'          =>     'lab_requests#lab_medical_records'
  get  'enter_radio_results'   =>     'radiology_requests#enter_radio_results'
  get  'results'          =>     'test_results#results'
  get  'patient_admission'          =>     'admissions#patient_admission'
  get  'admission_doc'          =>     'admissions#admission_doc'
  get 'patient_bill'    => 'bill_histories#patient_bill'
  get 'bill_open'    => 'bill_temps#bill_open'
  get 'outstanding'   => 'bill_temps#outstanding'
  get 'paid'    => 'bill_temps#paid'
  get 'delete_bill_record'    => 'bill_temps#delete_bill_record'

  get 'view_note'  => 'admissions#view_note'
  get 'view_discharge_note' => 'admissions#view_discharge_note'
  get  'view_nurse_record'          =>     'basic_med_records#view_nurse_record'
  post 'assign_to_a_doctor '  =>  'assign_patients#assign_to_a_doctor'
  get  'main_test'          =>     'test_results#main_test'
  get  'indi_radio_result'          =>     'radio_test_results#indi_radio_result'

  get 'close_request' =>  'medication_requests#close_request'
  get 'open_request'  =>   'medication_requests#open_request'

  get 'close_request_rad' =>  'radiology_requests#close_request_rad'
  get 'open_request_rad'  =>   'radiology_requests#open_request_rad'

  get  'order_records'          =>     'order_requests#order_records'
  get  'make_order'          =>     'order_requests#make_order'
  get  'view_order'          =>     'order_requests#view_order'

  get 'delete_order_record' =>     'order_requests#delete_order_record'

  get 'add_room'    =>      'admissions#add_room'
  get 'edit_room'    =>      'admissions#edit_room'
  post 'add_a_room'    =>      'admissions#add_a_room'

  get 'discharge_patient'    =>      'admissions#discharge_patient'
  get 'discharged_list'    =>      'admissions#discharged_list'
  get 'discharged_list_nurses'    =>      'admissions#discharged_list_nurses'
  get 'nurse_admission_list' => 'admissions#nurse_admission_list'

  get 'admission_vitals' => 'admissions#admission_vitals'
  get 'discharge_note' => 'admissions#discharge_note'
  post 'a_discharge_note' => 'admissions#a_discharge_note'

  get 'nurse_admission_vitals_history' =>  'basic_med_records#nurse_admission_vitals_history'
  get 'admission_vital_graph' =>  'basic_med_records#admission_vital_graph'
  get  'admission_basic_medical'          =>     'basic_med_records#admission_basic_medical'

  get  'doctor_admission_vitals_doc'          =>     'admissions#doctor_admission_vitals_doc'
  get  'view_doctor_admission_doc'          =>     'admissions#view_doctor_admission_doc'

  get 'close_order'  =>   'order_requests#close_order'

  get 'patient_appointment' => 'appointments#patient_appointment'

  get 'reception_patient' => 'patients#reception_patient'
  post 'reception_appointment' => 'appointments#reception_appointment'
  get 'doctor_appointment' => 'appointments#doctor_appointment'

  get 'open_med_temp'  => 'medication_temps#open_med_temp'
  get 'close_med_request'   => 'medication_temps#close_med_request'
  get 'delete_med_record'   => 'medication_temps#delete_med_record'

  get 'print_bill'   => 'bill_temps#print_bill'
  get 'print_all_bill'   => 'bill_temps#print_all_bill'

  post 'basic_vitals' => 'assign_patients#basic_vitals'

  get 'import_csv_file' => 'services_inventories#import_csv_file', as: :import_csv_file
  post 'import' => 'services_inventories#import', as: :import

   get  'view_vitals'          =>     'assign_patients#view_vitals'

   get 'print_labresults'   => 'lab_requests#print_labresults'
   get 'print_pharmacy'   => 'bill_temps#print_labresults'
   get 'print_xray'   => 'bill_temps#print_labresults'
   get 'print_ultrasound'   => 'bill_temps#print_labresults'

   get 'view_reciept'   => 'bill_temps#view_reciept'

   get 'set_orders'   => 'home#set_orders'

   get 'patient_profile'   => 'patients#patient_profile'

    get 'patient_treatment' => 'treatment_sheets#patient_treatment'
   get 'new_treatment' => 'treatment_sheets#new_treatment'

   get 'nurses_note' => 'basic_med_records#nurses_note'

   get 'new_nurse_note' => 'basic_med_records#new_nurse_note'
   get 'open_note' => 'basic_med_records#open_note'

   get 'fluids_intake' => 'fluids#fluids_intake'

   get 'new_fluids_intake' => 'fluids#new_fluids_intake'

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_confirm_dispense.html.erb
<%= simple_form_for(@dispensary, url: confirm_dispense_path) do |f| %>
<div id="pager">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">
          &times;
        </button>


        <h4 class="modal-title"> select all items</h4>
      </div>
      <div class="modal-body" id = 'check_form'>

                <div class="table-responsive">
                  <table class="table table-hover mb-0">
                    <thead>
                      <tr>

                        <th class="pt-0"> check box </th>
                        <th class="pt-0"> Item Name </th>
                        <th class="pt-0"> Quantity </th>
                        <th class="pt-0"> Manufacturer </th>
                        <th class="pt-0"> Selling Price </th>
                      </tr>

                    </thead>


                    <tbody>

                    <% if @store_items_save.nil? %>
                      <% " Empty Store" %>
                    <% else %>

                    <tr>


                      <%= @store_items_save.each do |vals| %>
                      <td><%= check_box_tag ("check_box[id][]") %> </td>
                      <td id="name_of_items"><%= vals.assigned_item_name  %></td>
                      <td id="quantity_use"><%= f.input :quantity, input_html: { multiple:true } ,label:false   %></td>
                      <td id="name_of_items"><%= vals.assigned_item_manufacturer  %></td>
                      <td id="name_of_items"><%= vals.assigned_item_selling_price  %></td>





                    </tr>

                    <% end %>

                  </tbody>
                </table>

                <div class="form-actions">

                  <%= f.button :submit, "Submit",class: 'btn btn-primary btn-lg', data: {"disable-with": "submit......"} %>
                </div>

                <% end %>

      </div>
    </div>
  </div>
</div>
<% end %>

app/views/home/assigned_requests.html.erb
# View is a simple form
<body class="sidebar-dark">
  <div class="main-wrapper">
    <div class="page-wrapper">
      <div class="page-content">
        <div class="search3"style="margin-top: 100px;">
          <p>
            <%=form_tag assigned_requests_path, method: :get,class:"lus" do %>

            <!-- <input  placeholder="Search for category" name="search" value=""/> -->
            <%= select_tag "category", options_from_collection_for_select(@show_categories, "id", "name")%>


            <%= submit_tag "Search" %>
            <% end %>
            </p>
        </div>

        <%= simple_form_for(@dispensary, url: confirm_dispense_path, :method => :get, :remote => true) do |f| %>
          <div class="col-lg-7 col-xl-8 stretch-card">
            <div class="card-req-y">
              <div class="card-body-special-e" style="text-align:center;">
                <div class="d-flex justify-content-between align-items-baseline mb-2">
                  <h6 class="card-title-e mb-0">Assigned Requests</h6>

                  <div class="dropdown mb-2">
                    <button class="btn p-0" type="button" id="dropdownMenuButton7" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <i class="icon-lg text-muted pb-3px" data-feather="more-horizontal"></i>
                    </button>

                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton7">
                      <a class="dropdown-item d-flex align-items-center" href="#"><i data-feather="eye" class="icon-sm mr-2"></i> <span class="">View</span></a>
                      <a class="dropdown-item d-flex align-items-center" href="#"><i data-feather="edit-2" class="icon-sm mr-2"></i> <span class="">Edit</span></a>
                      <a class="dropdown-item d-flex align-items-center" href="#"><i data-feather="trash" class="icon-sm mr-2"></i> <span class="">Delete</span></a>
                      <a class="dropdown-item d-flex align-items-center" href="#"><i data-feather="printer" class="icon-sm mr-2"></i> <span class="">Print</span></a>
                      <a class="dropdown-item d-flex align-items-center" href="#"><i data-feather="download" class="icon-sm mr-2"></i> <span class="">Download</span></a>
                    </div>
                  </div>
                </div>
                <div class="table-responsive">
                  <table class="table table-hover mb-0">
                    <button type="button" id="caty-button" class="btn btn-success" style="float: left; color:white;">Check All</button>
                    <thead>
                      <tr>
                        <th></th>
                          <th>Store inventory master</th>
                          <th>Store inventory categories</th>
                          <th>Quantity</th>
                          <th>User</th>
                          <th>Date assigned</th>
                          <th>Comments</th>
                          <th>Status</th>
                          <th>Store manager</th>
                          <th colspan="3"></th>
                      </tr>
                    </thead>
                    <tbody>
                      <% @assigned_requests.each do |assigned_request| %>
                        <tr>
                          <td><%= check_box_tag ("assigned_request[id][]"), checked_value = assigned_request.id %> </td>
                          <td><%= assigned_request.item_name %></td>
                          <td><%= assigned_request.category_name %></td>
                          <td><%= assigned_request.assigned_quantity %></td>
                          <td><%= assigned_request.requesting_user %></td>
                          <td><%= assigned_request.assigned_date %></td>
                          <td><%= assigned_request.comments %></td>
                          <td><%= assigned_request.assigned_status %></td>
                          <td><%= assigned_request.assigned_by_store_manager %></td>
                        </tr>
                      <% end %>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
          
          <div style="margin-top: 80px;">
            <%= will_paginate @assigned_requests %>
          </div>

          <%= f.button :submit, 'dispense', { 'data-toggle' =>  "modal", 'data-target' => '#modal-window', class: 'btn btn-primary btn-lg' } %>
        <% end %>
      </div>
    </div>
  </div>
</body>
        

<script>
  $('#caty-button').on("click", function(){
    var cbxs = $('input[type="checkbox"]');
    cbxs.prop("checked", !cbxs.prop("checked"));
  });
</script>

<!-- Modal Call  -->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">

    </div>
  </div>
</div>

app/views/home/confirm_dispense.js.erb
$("#myModal").find(".modal-content").html("<%= escape_javascript (render partial: 'assigned_requests/confirm_dispense') %>");
$("#myModal").modal();

app/views/home/index.html.erb
<body>





<section id="main-content">
<section class="wrapper">
<div class="panel-heading ui-sortable-handle">
					<span class="panel-icon">
                      <i class="fa fa-calendar-o"></i>
                    </span>
                    <span class="panel-title"> Daily Stats</span>
                </div>

<!-- <div id="myfirstchart" style="height: 250px;"></div> -->

<%#= content_tag :div, "", id: "patient_chart", data: {patients: @patients} %>

<%#= content_tag :div, "", id: "myfirstbar2", data: {patients: @patients} %>

 <!-- <div id="donut" style="height: 250px;"></div>  -->

<!-- <div id="myfirstchart2" style="height: 250px;"></div> -->

<div class="caty-caty">
    <button type="button" id="caty-button" class="btn btn-success" style="width:max-content;text-decoration:none;">
        <%= link_to 'Create Category', new_store_inventory_category_path %>
    </button>

    <button type="button" id="caty-button" class="btn btn-success" style="width:max-content; text-decoration:none;">
        <%= link_to 'Add Item',new_store_inventory_master_path %>
    </button>
</div>

<div class="four-grids">
					<div class="col-md-3 four-grid">
						<div class="four-agileits">
							<div class="icon">
								<i class="glyphicon glyphicon-user" aria-hidden="true"></i>
							</div>
							<div class="four-text">
								<h3>Total Clients</h3>
								<h4><%= @patient_stats %> </h4>
								
							</div>
							
						</div>
					</div>
					<div class="col-md-3 four-grid">
						<div class="four-agileinfo">
							<div class="icon">
								<i class="glyphicon glyphicon-list-alt" aria-hidden="true"></i>
							</div>
							<div class="four-text">
								<h3>New Registration</h3>
								<h4> <%= @lastday %> </h4>

							</div>
							
						</div>
					</div>
					<div class="col-md-3 four-grid">
						<div class="four-w3ls">
							<div class="icon">
								<i class="glyphicon glyphicon-list-alt" aria-hidden="true"></i>
							</div>
							<div class="four-text">
								<h3>Appointments</h3>
									<h4> <%= @dailyappointments %> </h4>	
							</div>
							
						</div>
					</div>
					<div class="col-md-3 four-grid">
						<div class="four-wthree">
							<div class="icon">
								<i class="glyphicon glyphicon-heart-empty" aria-hidden="true"></i>
							</div>
							<div class="four-text">
								<h3>Physician Visits</h3>
								<h4> <%= @dailyDoctor %> </h4>
								
							</div>
							
						</div>
					</div>
					<div class="clearfix"></div>
				</div>















	
		<div class="col-md-6 agile-calendar">
			<div class="calendar-widget">
                <div class="panel-heading ui-sortable-handle">
					<span class="panel-icon">
                      <i class="fa fa-calendar-o"></i>
                    </span>
                    <span class="panel-title"> Calendar Widget</span>
                </div>
				<!-- grids -->
					<div class="agile-calendar-grid">
						<div class="page">
							
							<div class="w3l-calendar-left">
								<div class="calendar-heading">
									
								</div>
								<div class="monthly" id="mycalendar"></div>
							</div>
							
							<div class="clearfix"> </div>
						</div>
					</div>
			</div>
		</div>
				
</section>
 <!-- footer -->
		  <div class="footer">
			<div class="wthree-copyright">
			  <p>© 2020 - Present | <a href="https://www.devdexsoftware">Devdex Software . All rights reserved </a></p>
			  	<!-- | Developed by <a href="https://www.devdex.software">Devdex Software -->
			</div>
		  </div>
  <!-- / footer -->
</section>
<!--main content end-->
</section>
<!-- calendar -->
	<script type="text/javascript" src="/assets/monthly.js"></script>
	<script type="text/javascript">
		$(window).load( function() {

			$('#mycalendar').monthly({
				mode: 'event',
				
			});

			$('#mycalendar2').monthly({
				mode: 'picker',
				target: '#mytarget',
				setWidth: '250px',
				startHidden: true,
				showTrigger: '#mytarget',
				stylePast: true,
				disablePast: true
			});

		switch(window.location.protocol) {
		case 'http:':
		case 'https:':
		// running on a server, should be good.
		break;
		case 'file:':
		alert('Just a heads-up, events will not work when run locally.');
		}

		});
	</script>


	<script type="text/javascript">

	new Morris.Line({
  // ID of the element in which to draw the chart.
  element: 'patient_chart',
  // Chart data records -- each entry in this array corresponds to a point on
  // the chart.
  data: $('#patient_chart').data('patients'),
  // The name of the data record attribute that contains x-values.
  xkey: 'created_at',
  // A list of names of data record attributes that contain y-values.
  ykeys: ['id'],
  // Labels for the ykeys -- will be displayed when you hover over the
  // chart.
  labels: ['Total No']
});
	</script>



	<script type="text/javascript">

	new Morris.Bar({
  element: 'myfirstbar2',
 data: $('#myfirstbar2').data('patients'),
  xkey: 'created_at',
  ykeys: ['id'],
  labels: ['Patient Total']
});

// 	</script>


	<script>
 new Morris.Donut({
  element: 'donut',
  data: [
    {label: "Download Sales", value: 12},
    {label: "In-Store Sales", value: 30},
    {label: "Mail-Order Sales", value: 20}
  ]
});

	</script>
</body>

app/views/home/item_purchase.html.erb
<body class="sidebar-dark">
  	<div class="main-wrapper">
      <div class="page-wrapper">
        	<div class="page-content">

<div class="col-lg-7 col-xl-8 stretch-card">
            <div class="card-req">
              <div class="card-body-special">
                <div class="d-flex justify-content-between align-items-baseline mb-2">
                  <h6 class="card-title mb-0">Items Purchased</h6>
                  <div class="dropdown mb-2">
                    <button class="btn p-0" type="button" id="dropdownMenuButton7" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <i class="icon-lg text-muted pb-3px" data-feather="more-horizontal"></i>
                    </button>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton7">
                      <a class="dropdown-item d-flex align-items-center" href="#"><i data-feather="eye" class="icon-sm mr-2"></i> <span class="">View</span></a>
                      <a class="dropdown-item d-flex align-items-center" href="#"><i data-feather="edit-2" class="icon-sm mr-2"></i> <span class="">Edit</span></a>
                      <a class="dropdown-item d-flex align-items-center" href="#"><i data-feather="trash" class="icon-sm mr-2"></i> <span class="">Delete</span></a>
                      <a class="dropdown-item d-flex align-items-center" href="#"><i data-feather="printer" class="icon-sm mr-2"></i> <span class="">Print</span></a>
                      <a class="dropdown-item d-flex align-items-center" href="#"><i data-feather="download" class="icon-sm mr-2"></i> <span class="">Download</span></a>
                    </div>
                  </div>
                </div>
                <div class="table-responsive">
                  <table class="table table-hover mb-0">
                    <thead>
                      <tr>

                        <th class="pt-0">Category Name</th>
                        <th class="pt-0">Item Name</th>
                        <th class="pt-0">Quantity</th>
                        <th class="pt-0">Cost Price</th>
                        <th class="pt-0">Date of Purchase </th>
</tr>
                    </thead>
                    <tbody>
                      <% @store_purchases.each do |items_puchase| %>
                      <tr>
                        <%# <!-- <td><%= check_box_tag "assigned_requests_id",new_assigned_request_path(:id =>items_puchase.id) %> </td>
                        <td><%= items_puchase.name %></td>
                        <td><%= items_puchase.item_name %></td>
                        <td><%= items_puchase.quantity %></td>
                        <td><%= items_puchase.cost_price %></td>
                        <td><%= items_puchase.date_of_purchase %></td>

                      </tr>
                      <% end %>
                    </tbody>


                  </table>

                </div>
                <div class="caty-catz">
                <button type="button" id="caty-button" class="btn btn-success" style="width:max-content;">
                    <%= link_to 'Create New Store Purchase',new_store_purchase_path  %>
                </button>
                </div>

              </div>
            </div>
          </div>
        </div>
      </div>

</div>


</body>

app/views/home/requests.html.erb
<body class="sidebar-dark">
  <div class="main-wrapper">
    <div class="page-wrapper">
      <div class="page-content">
        <div class="search3"style="margin-top: 100px;">
          <p>
            <%=form_tag requests_path, method: :get,class:"lus" do %>

            <!-- <input  placeholder="Search for category" name="search" value=""/> -->
             <%= select_tag "category", options_from_collection_for_select(@show_categories, "id", "name")%>


            <%= submit_tag "Search" %>
            <% end %>
            </p>
        </div>
<%= simple_form_for(@store_request, url: retrive_path) do |f| %>
<div class="col-lg-7 col-xl-8 stretch-card">
  <div class="card-req">
    <div class="card-body-special" style="margin-top: -25px;">
      <div class="d-flex justify-content-between align-items-baseline mb-2">
        <h6 class="card-title mb-0" style="font-size: x-large;">Received Requests</h6>

        <div class="caty-caty" style="float: right; margin-right: -500px;">
          <button type="button" id="caty-button" class="btn btn-success" style="width:max-content;">
            <%=link_to "Make A Request", new_store_request_path %>
          </button>
        </div>
        <div class="dropdown mb-2">
          <button class="btn p-0" type="button" id="dropdownMenuButton7" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="icon-lg text-muted pb-3px" data-feather="more-horizontal"></i>
          </button>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton7">
            <a class="dropdown-item d-flex align-items-center" href="#"><i data-feather="eye" class="icon-sm mr-2"></i> <span class="">View</span></a>
            <a class="dropdown-item d-flex align-items-center" href="#"><i data-feather="edit-2" class="icon-sm mr-2"></i> <span class="">Edit</span></a>
            <a class="dropdown-item d-flex align-items-center" href="#"><i data-feather="trash" class="icon-sm mr-2"></i> <span class="">Delete</span></a>
            <a class="dropdown-item d-flex align-items-center" href="#"><i data-feather="printer" class="icon-sm mr-2"></i> <span class="">Print</span></a>
            <a class="dropdown-item d-flex align-items-center" href="#"><i data-feather="download" class="icon-sm mr-2"></i> <span class="">Download</span></a>
          </div>
        </div>
      </div>
      <div class="table-responsive">
        <table class="table table-hover mb-0">
          <thead>
            <tr>
              <th> </th>
              <th class="pt-0">Category Name</th>
              <th class="pt-0">STORE MASTER ID </th>
              <th class="pt-0">Item Name </th>
              <th class="pt-0">Quantity Requested</th>
              <th class="pt-0">Date Requested</th>
              <th class="pt-0">Request User</th>
              <th class="pt-0">Comments</th>
              <th class="pt-0">Status</th>
            </tr>
          </thead>
          <tbody>
              <% @store_requests.each do |request_list| %>
            <tr class="tdd">
              <td><%= check_box_tag ("store_request[id][]"),checked_value = request_list.id %> </td>
              <td><%=request_list.category_name%></td>
              <td><%=request_list.store_inventory_master_id%></td>
              <td><%=request_list.item_name%></td>
              <td><%=request_list.requested_quantity%></td>
              <td><%=request_list.date_requested%></td>
              <td><%=request_list.requesting_user%></td>
              <td><%=request_list.comments%></td>
              <td><%=request_list.status%></td>

            </tr>

          </tbody>

          <% end %>

        </table>
        <div class="load-more-container">
         <%= link_to "Load More", requests_path, class: "load-more" %>
        </div>
      </div>

    </div>
    <div class="caty-catz" style="margin-left: 435px;">
      <button type="button" id="caty-button" class="btn btn-success" style="width:max-content; color:white;float: left;">
        <%= f.button :submit, 'Confirm Selected Items', :style =>"color:white;" %>
      </button>
    </div>
    </div>
    <% end %>

    </body>




<script>
$('#caty-button1').on("click", function(){
  var cbxs = $('input[type="checkbox"]');
  cbxs.prop("checked", !cbxs.prop("checked"));
});
</script>

app/views/home/retrive.js.erb
$("#myModal").find(".modal-content").html("<%= escape_javascript (render 'home/retrive') %>");
$("#myModal").modal();