config/routes.rb
Rails.application.routes.draw do
  devise_for :models
  resources :fluids
  resources :nurse_notes
  resources :treatment_sheets
  resources :nurse_procedures
  resources :incident_reports
  resources :radio_test_results
  resources :lab_order_lists
  resources :medication_temps
  resources :appointments
  resources :order_requests
  resources :order_masters
  resources :bill_temps do
    resource :download, only: [:show]
    resource :download2, only: [:show]
  end
  resources :admissions
  resources :service_inventory_histories
  resources :bill_histories
  resources :categories
  resources :services_inventories
  resources :test_results
  resources :radiology_requests
  resources :medication_requests
  resources :lab_requests
  resources :clinic_documents
  resources :basic_med_records
  resources :assign_patients
  resources :patients
  resources :roles
  devise_for :users
    resources :store_requests
    resources :dispensaries
  resources :store_inventory_masters
  resources :purchase_receipts
    resources :assigned_requests
    resources :store_inventory_categories
    resources :store_purchases
    resources :dispensaries
    resources :store_purchases do
      post :append, on: :collection
    end
  get 'home/index'

  get 'requests' => 'home#requests'

  get 'assigned_request_page' => 'home#assigned_requests'

  get 'receipts' => 'home#receipts'

  get 'item_purchase' => 'home#item_purchase'

  get 'categories' => 'home#categories'

  get 'dispensing' => 'home#dispensing'

  get 'confirm_dispense' => 'assigned_requests#confirm_dispense'
  get 'checkout' => 'store_requests#checkout'
  post 'retrive' => 'assigned_requests#retrive'
  get 'search' => 'store_inventory_masters#search'
  post 'back_to_form' => 'store_requests#back_to_form'
  post 'submit_to_dispense' => 'assigned_requests#submit_to_dispense'

  post 'modal_form' => 'store_requests#modal_form'

  get 'items_by_category/:store_inventory_category_id', to: 'store_requests#items_by_category'
  get '/store_requests_search' => 'store_requests#store_requests_search'

  get 'store_requests/update_items', as: 'update_items'

  root 'home#index'

  get '/users' => 'users#index'

  get '/users/new' => 'users#new', :as => 'new_user'
  get '/users/:id/edit' => 'users#edit', :as => 'edit_user'
  get '/users/:id' => 'users#show', :as => 'user'
  patch '/users/:id' => 'users#update', :as => 'update_user'
  patch '/patients/:id' => 'patients#update', :as => 'update_patient'
  post 'create_user' => 'users#create', as: :create_user

  post      'update_clinic_documents'                          =>     'clinic_documents#update_clinic_documents'

  get       'remove_contact'                          =>     'users#remove_contact'

  get       'patients_form'                          =>     'patients#patients_form'
  get  'show_patients'          =>     'patients#show_patients'
  get  'edit_patients'          =>     'patients#edit_patients'
  get  'edit_docs'          =>     'assign_patients#edit_docs'
  get  'assign_a_patient'          =>     'patients#assign_a_patient'
  get  'basic_medical'          =>     'assign_patients#basic_medical'
  get  'assign_a_patient2'          =>     'basic_med_records#assign_a_patient2'

  get  'procedure_list'          =>     'assign_patients#procedure_list'

  get 'view_procedure_record' =>     'nurse_procedures#view_procedure_record'

  get 'incident_form'  =>  'incident_reports#incident_form'
  get 'view_report'  =>  'incident_reports#view_report'

  get  'clinic_documentation'          =>     'assign_patients#clinic_documentation'
    get  'appt_documentation'          =>     'appointments#appt_documentation'
  get  'view_documentation'          =>     'assign_patients#view_documentation'
  get  'assign_lab'          =>     'assign_patients#assign_lab'
  get  'assign_med'          =>     'assign_patients#assign_med'
  get  'show_details'          =>     'assign_patients#show_details'
  get  'docs'          =>     'assign_patients#docs'
  get  'lab_docs'          =>     'lab_requests#lab_docs'
  get  'lab_form'          =>     'lab_requests#lab_form'
  get  'view_lab'          =>     'lab_requests#view_lab'
  get  'delete_lab_record'          =>     'lab_requests#delete_lab_record'
  get  'med_docs'          =>     'medication_requests#med_docs'
  get  'med_form'          =>     'medication_requests#med_form'
  get  'view_med'          =>     'medication_requests#view_med'
  get  'other_med'          =>     'medication_requests#other_med'
  get  'other_radio'          =>     'radiology_requests#other_radio'

  get  'radio_docs'          =>     'radiology_requests#radio_docs'
  get  'radio_form'          =>     'radiology_requests#radio_form'
  get  'view_radio'          =>     'radiology_requests#view_radio'
  get 'delete_radio_record'  =>     'radiology_requests#delete_radio_record'

  get  'other_lab'          =>     'lab_requests#other_lab'
  get  'lab_history'          =>     'lab_requests#lab_history'
  get  'enter_results'          =>     'lab_requests#enter_results'
  get  'lab_medical_records'          =>     'lab_requests#lab_medical_records'
  get  'enter_radio_results'   =>     'radiology_requests#enter_radio_results'
  get  'results'          =>     'test_results#results'
  get  'patient_admission'          =>     'admissions#patient_admission'
  get  'admission_doc'          =>     'admissions#admission_doc'
  get 'patient_bill'    => 'bill_histories#patient_bill'
  get 'bill_open'    => 'bill_temps#bill_open'
  get 'outstanding'   => 'bill_temps#outstanding'
  get 'paid'    => 'bill_temps#paid'
  get 'delete_bill_record'    => 'bill_temps#delete_bill_record'

  get 'view_note'  => 'admissions#view_note'
  get 'view_discharge_note' => 'admissions#view_discharge_note'
  get  'view_nurse_record'          =>     'basic_med_records#view_nurse_record'
  post 'assign_to_a_doctor '  =>  'assign_patients#assign_to_a_doctor'
  get  'main_test'          =>     'test_results#main_test'
  get  'indi_radio_result'          =>     'radio_test_results#indi_radio_result'

  get 'close_request' =>  'medication_requests#close_request'
  get 'open_request'  =>   'medication_requests#open_request'

  get 'close_request_rad' =>  'radiology_requests#close_request_rad'
  get 'open_request_rad'  =>   'radiology_requests#open_request_rad'

  get  'order_records'          =>     'order_requests#order_records'
  get  'make_order'          =>     'order_requests#make_order'
  get  'view_order'          =>     'order_requests#view_order'

  get 'delete_order_record' =>     'order_requests#delete_order_record'

  get 'add_room'    =>      'admissions#add_room'
  get 'edit_room'    =>      'admissions#edit_room'
  post 'add_a_room'    =>      'admissions#add_a_room'

  get 'discharge_patient'    =>      'admissions#discharge_patient'
  get 'discharged_list'    =>      'admissions#discharged_list'
  get 'discharged_list_nurses'    =>      'admissions#discharged_list_nurses'
  get 'nurse_admission_list' => 'admissions#nurse_admission_list'

  get 'admission_vitals' => 'admissions#admission_vitals'
  get 'discharge_note' => 'admissions#discharge_note'
  post 'a_discharge_note' => 'admissions#a_discharge_note'

  get 'nurse_admission_vitals_history' =>  'basic_med_records#nurse_admission_vitals_history'
  get 'admission_vital_graph' =>  'basic_med_records#admission_vital_graph'
  get  'admission_basic_medical'          =>     'basic_med_records#admission_basic_medical'

  get  'doctor_admission_vitals_doc'          =>     'admissions#doctor_admission_vitals_doc'
  get  'view_doctor_admission_doc'          =>     'admissions#view_doctor_admission_doc'

  get 'close_order'  =>   'order_requests#close_order'

  get 'patient_appointment' => 'appointments#patient_appointment'

  get 'reception_patient' => 'patients#reception_patient'
  post 'reception_appointment' => 'appointments#reception_appointment'
  get 'doctor_appointment' => 'appointments#doctor_appointment'

  get 'open_med_temp'  => 'medication_temps#open_med_temp'
  get 'close_med_request'   => 'medication_temps#close_med_request'
  get 'delete_med_record'   => 'medication_temps#delete_med_record'

  get 'print_bill'   => 'bill_temps#print_bill'
  get 'print_all_bill'   => 'bill_temps#print_all_bill'

  post 'basic_vitals' => 'assign_patients#basic_vitals'

  get 'import_csv_file' => 'services_inventories#import_csv_file', as: :import_csv_file
  post 'import' => 'services_inventories#import', as: :import

   get  'view_vitals'          =>     'assign_patients#view_vitals'

   get 'print_labresults'   => 'lab_requests#print_labresults'
   get 'print_pharmacy'   => 'bill_temps#print_labresults'
   get 'print_xray'   => 'bill_temps#print_labresults'
   get 'print_ultrasound'   => 'bill_temps#print_labresults'

   get 'view_reciept'   => 'bill_temps#view_reciept'

   get 'set_orders'   => 'home#set_orders'

   get 'patient_profile'   => 'patients#patient_profile'

    get 'patient_treatment' => 'treatment_sheets#patient_treatment'
   get 'new_treatment' => 'treatment_sheets#new_treatment'

   get 'nurses_note' => 'basic_med_records#nurses_note'

   get 'new_nurse_note' => 'basic_med_records#new_nurse_note'
   get 'open_note' => 'basic_med_records#open_note'

   get 'fluids_intake' => 'fluids#fluids_intake'

   get 'new_fluids_intake' => 'fluids#new_fluids_intake'

end

app/models/basic_med_record.rb
class BasicMedRecord < ApplicationRecord
  
  def self.patient_no_search(card_no)
  card_no = "%#{card_no}%"
  where('card_no LIKE ?', card_no) 
end


 def self.date_search(start = nil, ended = nil)
    if start && ended
      where(created_at: "#{start} 00:00:00".."#{ended} 23:59:59")
    else
      all
      end
 end


def self.mobile_number_search(mobile_number)
  mobile_number = "%#{mobile_number}%"
  # where("customer_name LIKE ?",mobile_number)
  where('mobile_number LIKE ?', mobile_number)
end


def self.name_search(name)
  name = "%#{name}%"
  where('surname LIKE ?', name)
end
end

app/helpers/basic_med_records_helper.rb
module BasicMedRecordsHelper
end

app/views/basic_med_records/_admission_vital_graph.html.erb
  <div class="row2">
    <div class="col-md-12 col-md-offset-0">

      <%#= content_tag :div, "", id: "myfirstchart", data: {records: @basic_med_records} %>

    <!--  <div id="myfirstchart" style="height: 250px;"></div> -->

    <%= line_chart (@highcharts_data), xtitle: "Time", ytitle: "Temperature"%>
          
  </div>

 <script type="text/javascript">

new Morris.Line({
  // ID of the element in which to draw the chart.
  element: 'myfirstchart',
  // Chart data records -- each entry in this array corresponds to a point on
  // the chart.
  data: $('#myfirstchart').data('records'),
  // The name of the data record attribute that contains x-values.
  xkey: 'temp',
  // A list of names of data record attributes that contain y-values.
  ykeys: ['respiratory_rate'],
  // Labels for the ykeys -- will be displayed when you hover over the
  // chart.
  labels: ['Respiratory Rate']
});

</script>


</div>





  

app/views/basic_med_records/_assign_a_patient2.html.erb
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

   <div class="table-agile-info">

 
   <%= simple_form_for(@assign_to_doctor, :url =>{:controller => 'assign_patients', :action => 'assign_to_a_doctor'}) do |f| %>

 
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="container">
        <fieldset>
                <div class="">
                        <div class="col-md-5">
                         <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token.to_s %>"> 

                             


  <div class="ggg">
 
    <%#= f.input :personnel_id,label: "Select a Doctor", collection: User.where("role_id = 1"), label_method: :fullname, value_method: :role_id,class: "ggg" %>   <!-- This goes to all doctors -->

    <%= f.input :personnel_id,label: "Select a Doctor", collection: User.where("role_id = 1"), label_method: :fullname, value_method: :id,class: "ggg" %>  <!-- this goes to a specific doctor -->
  </div>


   <div class="form-inputs">
    <%= f.input :user_id, :as=> :hidden,input_html: {value: current_user.id} %>
    <% logger.info "role in index: #{current_user.role_id}" %>

</div>

  <div class="form-inputs">
    <%= f.input :role_id, :as=> :hidden,input_html: {value: current_user.role_id} %>
    <% logger.info "role in index: #{current_user.role_id}" %>

</div>

<div class="form-inputs">
  <% if (defined?(@patient_id)).nil? %>
    <%= f.input :patient_id,:as=> :hidden %>
   <% else  %>
  <%= f.input :patient_id, :as=> :hidden,input_html: {value: @patient_id} %>
<% logger.info "Rnning" %>
 <% logger.info "patient in index: #{@patient_id}" %>
<% end %>
  </div>


  <div class="form-inputs">
  <% if (defined?(@basic_med_id)).nil? %>
    <%= f.input :basic_medical_record_id,:as=> :hidden %>
   <% else  %>
  <%= f.input :basic_medical_record_id, :as=> :hidden,input_html: {value: @basic_med_id} %>
<% logger.info "Rnning" %>
 <% logger.info "patient in index: #{@patient_id}" %>

  </div>


   



  <div class="form-inputs">
    <%= f.input :status, :as=> :hidden, input_html: {value: 1 } %>

  </div>



<center>
   <div class="form-actions">
    <%#= f.button :submit %>
     <%= f.submit "Assign Patient" ,:class =>'"btn btn-primary btn-sm btn3d"'%>
  </div>
</center>
<% end %>
<% end %>

</div>





<script type="text/javascript">
        $(function() {
        $('#datetimepicker6').datetimepicker({
        format : 'YYYY-MM-D H:m:s'
        });
        $("#datetimepicker6").on("dp.change", function(e) {
        $('#datetimepicker7').data("DateTimePicker").minDate(e.date);
        });
        });

        $(document).ready(function() {
        $("#sent_status").show();
        });
        
       
        
</script>

app/views/basic_med_records/_form.html.erb
<%= simple_form_for(@basic_med_record) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :patient_id %>
    <%= f.input :blood_pressure %>
    <%= f.input :pulse %>
    <%= f.input :temp %>
    <%= f.input :respiratory_rate %>
    <%= f.input :user_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/basic_med_records/_view_nurse_record.html.erb
               <% if (defined?(@documents)).nil? %>
                  <% else  %>

  <div class="row">
    <div class="col-md-12 col-md-offset-0">
      <table class="custab table table-striped table-hover table-bordered">
 
      
<br>
     
                             
<br>
<br>
   

            <td style="background-color:rgba(110, 129, 149, 0.96);color:#fbfbff">Blood pressure</td>
            <td style="background-color:rgba(251, 251, 255, 0.96);color:#000000"><%=   @documents[0].blood_pressure %></td>
             
          </tr>
           <tr>
              
            <td style="background-color:rgba(110, 129, 149, 0.96);color:#fbfbff">pulse</td>
            <td style="background-color:rgba(251, 251, 255, 0.96);color:#000000"><%=   @documents[0].pulse %></td>
             
          </tr>
           <tr>
              
            <td style="background-color:rgba(110, 129, 149, 0.96);color:#fbfbff">Temp</td>
            <td style="background-color:rgba(251, 251, 255, 0.96);color:#000000"><%=   @documents[0].temp %></td>
             
          </tr>
           <tr>
              
            <td style="background-color:rgba(110, 129, 149, 0.96);color:#fbfbff">Respiratory Rate</td>
            <td style="background-color:rgba(251, 251, 255, 0.96);color:#000000"><%=   @documents[0].respiratory_rate %></td>
             
          </tr>

           <tr>
              
            <td style="background-color:rgba(110, 129, 149, 0.96);color:#fbfbff">Weight </td>
            <td style="background-color:rgba(251, 251, 255, 0.96);color:#000000"><%=   @documents[0].weight %></td>
             
          </tr>


           <tr>
              
            <td style="background-color:rgba(110, 129, 149, 0.96);color:#fbfbff">Height</td>
            <td style="background-color:rgba(251, 251, 255, 0.96);color:#000000"><%=   @documents[0].height %></td>
             
          </tr>


           <tr>
              
            <td style="background-color:rgba(110, 129, 149, 0.96);color:#fbfbff">Saturation</td>
            <td style="background-color:rgba(251, 251, 255, 0.96);color:#000000"><%=   @documents[0].saturation %></td>
             
          </tr>



    
            
          



 </table>

     <p style="background-color:rgba(110, 129, 149, 0.96);color:#fbfbff">Complaints</p>
            <p style="background-color:rgba(251, 251, 255, 0.96);color:#000000;overflow-wrap: break-word;"><%=   @documents[0].complaints %><p>
     
          
  </div>
</div>

<% end %>

app/views/basic_med_records/admission_basic_medical.js.erb
$("#basic").html("<%= escape_javascript(render 'basic_med_records/admission_basic_medical') %>");
// $("#modal-window").html("<%= escape_javascript(render 'patients/assign_a_patient') %>");
 $('#modal-window').modal('show');

app/views/basic_med_records/admission_vital_graph.js.erb
$("#graph").html("<%= escape_javascript(render 'basic_med_records/admission_vital_graph') %>");
 $('#modal-window').modal('show');

 chart.render();

app/views/basic_med_records/assign_a_patient2.js.erb
$("#hey1").html("<%= escape_javascript(render 'basic_med_records/assign_a_patient2') %>");
// $("#modal-window").html("<%= escape_javascript(render 'patients/assign_a_patient') %>");
 $('#modal-window').modal('show');

app/views/basic_med_records/edit.html.erb
<h1>Editing Basic Med Record</h1>

<%= render 'form' %>

<%= link_to 'Show', @basic_med_record %> |
<%= link_to 'Back', basic_med_records_path %>

app/views/basic_med_records/new.html.erb
<h1>New Basic Med Record</h1>

<%= render 'form' %>

<%= link_to 'Back', basic_med_records_path %>

app/views/basic_med_records/nurse_admission_vitals_history.html.erb
<section id="main-content">


  <section class="wrapper">
<%= line_chart (@highcharts_data), xtitle: "Time", ytitle: "Temperature"%>

    <div class="table-agile-info">
 <div class="panel panel-default">
    <div class="panel-heading">
   VITALS FOR <%= @patient_records.other_names + " " + @patient_records.surname %> (<%= @patient_records.card_no %>)
    </div>
    <div style="overflow-x:auto;">
      <table class="table" ui-jq="footable" ui-options='{
        "paging": {
          "enabled": true
        },
        "filtering": {
          "enabled": true
        },
        "sorting": {
          "enabled": true
        }}'>
        <thead>
          <tr>

       <th>Temperature</th>
       <th>Blood Pressure</th>
       <th>Pulse</th>
         <th>Respiratory Rate</th>
       
        <th>Date/Time</th>
      <th>Nurse</th>
     
      <th colspan="3">  <%= link_to  'New Vitals (admission) ', admission_basic_medical_path(:id => @patient_id), {:remote => true, :class => "btn btn-primary btn-sm" ,'data-toggle' =>  "modal", 'data-target' => '#myModal2'} %></th>

          </tr>
        </thead>
        <tbody>
      <% #count=1 %>

           <% @basic_med_records.each do |basic_med_record| %>
      <tr>
       
        <td id="whitespace"><%= basic_med_record.temp%></td>
        <td id="whitespace"><%= basic_med_record.blood_pressure%></td>
        <td id="whitespace"><%= basic_med_record.pulse%></td>
        <td id="whitespace"><%= basic_med_record.respiratory_rate%></td>
         <td id="whitespace"><%= basic_med_record.created_at.strftime("%B %d, %Y, %H:%M") %></td>
        <td id="whitespace"><%= basic_med_record.fullname %></td>
        
        <td id="whitespace"><%= link_to 'View More Record', view_nurse_record_path(:id => basic_med_record.created_at),{:remote => true, class:'"btn btn-warning btn-sm btn3d"','data-toggle' =>  "modal",'data-target' => '#myModal5'} %></td> 
        


      </tr>
       <%# count=count+1 %> 
    <% end %>
       
           

        </tbody>
      </table>

 <center>


 <%= link_to  'New Vitals (admission) ', admission_basic_medical_path(:id => @patient_id), {:remote => true, :class => "btn btn-primary btn-sm" ,'data-toggle' =>  "modal", 'data-target' => '#myModal2'} %>


  <%#= link_to  'View Vital Graph ', admission_vital_graph_path(:id => @patient_id), {:remote => true, :class => "btn btn-success btn-sm" ,'data-toggle' =>  "modal", 'data-target' => '#myModal6'} %>

     </center>   
     <br>  




    </div>
  </div>
</div>
</section>


 
</section>









<div  id="myModal2" class="modal fade" role="dialog">
  <div class="modal-dialog">

   
    <div class="modal-content" >
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title"> Create Patient Vitals (Admission)</h4>
      </div>
      <div class="modal-body" id = 'basic'>
      <%= render "admission_basic_medical" %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>





<div id="myModal5" class="modal fade" role="dialog">
  <div class="modal-dialog">


    <div class="modal-content" >
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title"> Nurse Clinical Documents / Vitals (Admission)</h4>
      </div>
      <div class="modal-body" id = 'fire'>
      <%= render "view_nurse_record" %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>





<div id="myModal6" class="modal fade" role="dialog">
  <div class="modal-dialog">


    <div class="modal-content" >
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title"> VITAL GRAPH</h4>
      </div>
      <div class="modal-body" id = 'graph'>
      <%#= render "admission_vital_graph" %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>







 


  </script>

app/views/basic_med_records/nurses_note.html.erb
<section id="main-content">
  <section class="wrapper">
     
    <div class="table-agile-info">
 <div class="panel panel-default">

                             
<br>
<br>
    <div class="panel-heading">
    Nurses Note
    </div>
    
    <div style="overflow-x:auto;">
      <table  class="table" ui-jq="footable" ui-options='{
        "paging": {
          "enabled": true
        },
        "filtering": {
          "enabled": true
        },
        "sorting": {
          "enabled": true
        }}'>
        <thead>
         <tr>
    <!--    <th>Nurses Note</th> -->
                <th>Time</th>
                <th>Written by</th>
      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
     <% @nurse_notes.each do |nurse_note| %>
      <tr>
        <!-- <td ><%#= nurse_note.notes %></td> -->
        <td><%= nurse_note.time.strftime("%B %d, %Y %H:%M") %></td>
         <td><%= nurse_note.fullname %></td>
         <td ><%= link_to 'Open Note', open_note_path(:id => nurse_note.created_at), {:remote => true, class:'"btn btn-warning btn-sm btn3d"','data-toggle' =>  "modal", 'data-target' => '#myModal4'} %></td>
        
 
      </tr>
    <% end %>
  </tbody>
</table>

<br>


       <center>

<%= link_to 'Create Nurse Note', new_nurse_note_path(:id => @patient_id), {:remote => true, :class => "btn btn-primary btn-sm" ,'data-toggle' =>  "modal", 'data-target' => '#myModal'} %>

     </center>   

  </div>
</div>
</section>
 
</section>


<div id="myModal4" class="modal fade" role="dialog">
  <div class="modal-dialog">


    <div class="modal-content" >
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title"> Notes</h4>
      </div>
      <div class="modal-body" id = 'fire'>
      <%= render "open_note" %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>





<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <div class="modal-content" >
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title"> Create Note</h4>
      </div>
      <div class="modal-body" >
      <%= render "new_nurse_note" %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>

app/views/basic_med_records/open_note.js.erb
$("#fire").html("<%= escape_javascript(render 'basic_med_records/open_note') %>");
 $('#modal-window').modal('show');

app/views/basic_med_records/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Patient:</strong>
  <%= @basic_med_record.patient_id %>
</p>

<p>
  <strong>Blood pressure:</strong>
  <%= @basic_med_record.blood_pressure %>
</p>

<p>
  <strong>Pulse:</strong>
  <%= @basic_med_record.pulse %>
</p>

<p>
  <strong>Temp:</strong>
  <%= @basic_med_record.temp %>
</p>

<p>
  <strong>Respiratory rate:</strong>
  <%= @basic_med_record.respiratory_rate %>
</p>

<p>
  <strong>User:</strong>
  <%= @basic_med_record.user_id %>
</p>

<%= link_to 'Edit', edit_basic_med_record_path(@basic_med_record) %> |
<%= link_to 'Back', basic_med_records_path %>

app/views/basic_med_records/view_nurse_record.js.erb
$("#fire").html("<%= escape_javascript(render 'basic_med_records/view_nurse_record') %>");
// $("#modal-window").html("<%= escape_javascript(render 'basic_med_records/view_nurse_record') %>");
 $('#modal-window').modal('show');